#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.generative.ai.rest.dto.v1_0.GenerativeAIResponse
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Generative.AI.REST)
osgi.jaxrs.resource=true