/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.generative.ai.task.model.impl;

import com.liferay.generative.ai.task.model.TaskDefinition;
import com.liferay.generative.ai.task.service.TaskDefinitionLocalServiceUtil;

/**
 * The extended model base implementation for the TaskDefinition service. Represents a row in the &quot;TaskDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskDefinitionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskDefinitionImpl
 * @see TaskDefinition
 * @generated
 */
public abstract class TaskDefinitionBaseImpl
	extends TaskDefinitionModelImpl implements TaskDefinition {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task definition model instance should use the <code>TaskDefinition</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TaskDefinitionLocalServiceUtil.addTaskDefinition(this);
		}
		else {
			TaskDefinitionLocalServiceUtil.updateTaskDefinition(this);
		}
	}

}